[aws]
region = "eu-west-1"

[dynamodb.table.main]
partition_key = { name = "pk", type = "string" }
sort_key = { name = "sk", type = "string" }

[dynamodb.table.sessions]
partition_key = { name = "pk", type = "string" }
sort_key = { name = "sk", type = "string" }

[dynamodb.seeds]
folder = "dynamodb/seeds"

[lambda."/"]
handler = "src/lambda.handler"
methods = ["ANY"]

